version: "3.9"

services:
  model:
    build:
      context: .
      dockerfile: Dockerfile.model
    container_name: model-server
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    environment:
      - MODEL_PATH=/models/gemma-3-1b-it-Q4_K_M.gguf

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: bot-app
    ports:
      - "5001:8070"
    environment:
      - MODEL_SERVER=http://model:8000
      - DB_HOST=db          # <- database hostname
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - model
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
